clickhouse:
  ch1:
    db: default
    host: bj-dcs-009
    port: 9011
    username: default
    password: coohua
kafka:
  kafka1:
    brokers: spark015:9092
    sasl:
      password:
      username:
common:
  bufferSize: 90000
  flushInterval: 5
  logLevel: info

Raven:
  dsn: http://ffee003c7163475e8676694055170419@172.16.11.212:9876/15
  username: pc
  email: 879484963@qq.com

