clickhouse:
  ch1:
    db: default
    host: bj-dcs-009:9011,bj-dcs-010:9011
    port: 9011
    username: default
    password: coohua
kafka:
  kafka1:
    brokers: spark015:9092
    sasl:
      password:
      username:
  kafka2:
    brokers: bj-dcs-005:9092
    sasl:
      password:
      username:

common:
  pprof: 0.0.0.0:6050
  bufferSize: 90000
  flushInterval: 5
  logLevel: warn

Raven:
  dsn: http://ffee003c7163475e8676694055170419@172.16.11.212:9876/15
  username: pc
  email: 879484963@qq.com

