tasks:
  - name: ad_task
    kafka: kafka1
    topic: pc_test
    consumerGroup: test_g1
    clickhouse: ch1
    # current support（gjson,ecp） gjson原生json解析, ecp业务广告ecp解析
    parser: ecp
    tableName: newsearn_test
    bufferSize: 90000
    Dims:
       - name: logday
         type: String
         jsonfield: udate.logday
       - name: userid
         type: String
         jsonfield: udate.hour
       - name: price
         type: String
         jsonfield: udate.minute



